### ISSUE TITLE
Problem with a Webcam

### ISSUE THREAD

**Issue by 1975431535566** [ihrapsa/OctoWrt#34]
Hello, i have a problem. i don't see how i can configurate the webcam. I can't find any description on how to make it or how to set it up, because I was planning to make timelapses using the octolapse plugin.

**Comment by ihrapsa** [comment]
I don’t recommend using plugins on the box. Many of them will fail to install probably because of a dependency issue and if you manage to fix that it will bloat octoprint even more. If you want to take snapshots to build a Timelapse afterwards you don’t need octolapse. There’s a tab called Timelapse already available by default

**Comment by 1975431535566** [comment]
Ok, I managed to install octolapse already, but even with time laps and control I can't see the webcam, I also entered the ip. But I can't find a way to see the webcam even on the control card. Thanks for the advice about the box! 😁

**Comment by ihrapsa** [comment]
Check if mjpg-streamer is running. It’s on `http://your-box-ip:8080`

**Comment by 1975431535566** [comment]
Ok, i don't have make nothing, and now is running. Thank you
